
    BoxLayout:
        orientation: 'vertical'
        BoxLayout:
            orientation: 'horizontal'
            size_hint_y: 1
            height: 32
            Spinner:
                size_hint_x: None
                width:100
                id: sp0
                text: 'File'
                on_text: root.do_menu()
            Label:
                id: path0
                text: './primrose.png'
        BoxLayout:
            orientation: 'vertical'
            size_hint_y: 8
            # ラベル
            Label:
                id: label1
                text_size: self.size
                font_size: 20
                text: 'ABC' # root.res['GRC_TEXT'][0]
                halign: 'center'
                valign: 'center'
            BoxLayout:
                Button:
                    id: allclear
                    text: "AC"
                    font_size: 25
                    size_hint: (.25, 1)
                Button:
                    id: eraser
                    text: "Eraser"
                    font_size: 25
                    size_hint: (.25, 1)
                Button:
                    id: framing
                    text: "Framing"
                    font_size: 25
                    size_hint: (.5, 1)
            BoxLayout:
                Button:
                    id: background0
                    text: "0 - Sure Background"
                    font_size: 20
                Button:
                    id: foreground1
                    text: "1 - Sure Foreground"
                    font_size: 20
            BoxLayout:
                Button:
                    id: background2
                    text: "2 - Possibly Background"
                    font_size: 20
                Button:
                    id: foreground3
                    text: "3 - Possibly Foreground"
                    font_size: 20
            BoxLayout:
                Button:
                    id: number0
                    text: "0"
                    font_size: 25
                Button:
                    id: number1
                    text: "1"
                    font_size: 25
                Button:
                    id: number2
                    text: "2"
                    font_size: 25
                Button:
                    id: number3
                    text: "3"
                    font_size: 25
            BoxLayout:
                Button:
                    id: rot90
                    text: "Rot+90"
                    font_size: 25
                Button:
                    id: rot270
                    text: "Rot-90"
                    font_size: 25
                Button:
                    id: plus
                    text: "+"
                    font_size: 30
                Button:
                    id: minus
                    text: "-"
                    font_size: 40